### ISSUE TITLE
first set of comments/questions

### ISSUE THREAD

**Issue by agladstein** [CyVerse-learning-materials/container_camp_workshop_2018#1]
- https://cyverse-container-camp-workshop-2018.readthedocs-hosted.com/en/latest/atmosphere/boot.html
In step 3 of Booting a Atmosphere Computer Instance for your use, it says "Name it something simple and select ‘m1.medium’", but the picture shows a tiny instance, and there is nothing to click that is "m1.medium". Is it supposed to be a medium1 instance? 

- https://cyverse-container-camp-workshop-2018.readthedocs-hosted.com/en/latest/docker/dockerintro.html#running-docker-containers-from-prebuilt-images
You say "In the demo above, you used the docker pull command to download the alpine image"
Do you show a demo?

- how do you see the static site from atmo instance?

- https://cyverse-container-camp-workshop-2018.readthedocs-hosted.com/en/latest/docker/dockerintro.html#flask-app
Which directory should the Dockerfile be in?

- https://cyverse-container-camp-workshop-2018.readthedocs-hosted.com/en/latest/docker/dockeradvanced.html#tag-the-image-that-you-want-to-push
`docker tag myfirstapp $REGISTRY/$(whoami)/myfirstapp:1.0` didn't work. needed
`docker tag agladstein/myfirstapp $REGISTRY/$(whoami)/myfirstapp:1.0`

- https://cyverse-container-camp-workshop-2018.readthedocs-hosted.com/en/latest/docker/dockeradvanced.html#create-an-automated-build
```
agladstein@vm142-45:~/flask-app$ git remote add origin https://github.com/agladstein/flask-app.git
agladstein@vm142-45:~/flask-app$ git push -u origin master
Username for 'https://github.com': agladstein
Password for 'https://agladstein@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/agladstein/flask-app.git/' not found
```

- https://cyverse-container-camp-workshop-2018.readthedocs-hosted.com/en/latest/docker/dockeradvanced.html#start-a-container-with-a-volume
```
        "Mounts": [
            {
                "Type": "volume",
                "Name": "myvol2",
                "Source": "/var/lib/docker/volumes/myvol2/_data",
                "Destination": "/app",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
```
Is Mode z okay?

- https://cyverse-container-camp-workshop-2018.readthedocs-hosted.com/en/latest/docker/dockeradvanced.html#docker-compose-for-multi-container-apps
```
docker-compose up -d
The program 'docker-compose' is currently not installed. To run 'docker-compose' please ask your administrator to install the package 'docker-compose'
```

**Comment by upendrak** [comment]
@agladstein thanks for your comments/questions. I think I have fixed all of them. Please let me know if you have any trouble with the fixes. Thanks
