### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dshyshlov** [CyVerse-learning-materials/container_camp_workshop_2018#12]
https://cyverse-container-camp-workshop-2018.readthedocs-hosted.com/en/latest/container_scaling/containerscaling_osg.html#exercise-2-containerized-job-default-image

There is a typo in "condor" command in the following block:

$ condor_q
$ codnor_q -nobatch

**Comment by upendrak** [comment]
Thanks @dshyshlov. Fixed it..
